FROM crocodilestick/calibre-web-automated:latest

RUN rm /usr/bin/kepubify && \
    curl https://github.com/pgaskin/kepubify/releases/latest/download/kepubify-linux-arm64 -o /usr/bin/kepubify && \
    chmod +x /usr/bin/kepubify


