services:
  coredns:
    container_name: coredns
    image: coredns/coredns
    restart: unless-stopped
    volumes:
      - ./config/coredns/Corefile:/Corefile:ro
    networks:
      homelab:
        ipv4_address: 172.20.10.254

  homepage:
    container_name: homepage
    restart: unless-stopped
    image: ghcr.io/gethomepage/homepage
    volumes:
      - ./config/homepage/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - ./config/homepage/docker.yaml:/app/config/docker.yaml:ro
      - ./config/homepage/services.yaml:/app/config/services.yaml:ro
      - ./config/homepage/settings.yaml:/app/config/settings.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: lab.teixe.es
      HOMEPAGE_VAR_CALIBRE_PASSWORD: ${HOMEPAGE_VAR_CALIBRE_PASSWORD}
    networks:
      - homelab

  caddy:
    container_name: caddy
    build: ./config/caddy/
    restart: unless-stopped
    # See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
    cap_add:
      - net_admin
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    networks:
      - homelab

  calibre-web-automated:
    container_name: calibre-web-automated
    image: crocodilestick/calibre-web-automated
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./data/calibre/config:/config
      - ./data/calibre/ingest:/cwa-book-ingest
      - ./data/calibre/library:/calibre-library
    networks:
      - homelab

  cwa-book-downloader:
    container_name: cwa-book-downloader
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader
    depends_on:
      - calibre-web-automated
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: en,es
      USE_BOOK_TITLE: true
      TZ: Europe/Madrid
      APP_ENV: prod
      UID: 1000
      GID: 100
      CWA_DB_PATH: /auth/app.db
    restart: unless-stopped
    volumes:
      - ./data/calibre/ingest:/cwa-book-ingest
      - ./data/calibre/config/app.db:/auth/app.db:ro
    networks:
      - homelab

  openbooks:
    container_name: openbooks
    image: evanbuss/openbooks
    command: --persist --name ${OPENBOOKS_IRC_NAME}
    restart: unless-stopped
    volumes:
      - ./data/calibre/ingest:/books/books
    networks:
      - homelab

  actual-server:
    container_name: actual-server
    image: actualbudget/actual-server
    restart: unless-stopped
    volumes:
      - ./data/actual:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - homelab

  kitchenowl:
    container_name: kitchenowl
    image: tombursch/kitchenowl
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=${KITCHENOWL_JWT_SECRET_KEY}
    volumes:
      - ./data/kitchenowl:/data
    networks:
      - homelab

  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M # Recommended by docs
    volumes:
      - ./data/mealie:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      BASE_URL: https://mealie.lab.teixe.es
    networks:
      - homelab

  adventurelog-web:
    container_name: adventurelog-web
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    restart: unless-stopped
    env_file: config/adventurelog/.env
    depends_on:
      - adventurelog-server
    networks:
      - homelab

  adventurelog-db:
    image: tobi312/rpi-postgresql-postgis:15-3.3-alpine-arm
    container_name: adventurelog-db
    restart: unless-stopped
    env_file: config/adventurelog/.env
    volumes:
      - ./data/adventurelog/postgres:/var/lib/postgresql/data/
    networks:
      - homelab

  adventurelog-server:
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-server
    restart: unless-stopped
    env_file: config/adventurelog/.env
    depends_on:
      - adventurelog-db
    volumes:
      - ./data/adventurelog/adventurelog:/code/media/
    networks:
      - homelab

networks:
  homelab:
    name: homelab
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 172.20.10.0/24
          gateway: 172.20.10.1
