name: Sync Tailscale ACLs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - policy.hujson

jobs:
  acls:
    name: Sync Tailscale ACLs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            policy.hujson
          sparse-checkout-cone-mode: false

      - name: Test ACL
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET}}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: test

      - name: Deploy ACL
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET}}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply
